layout_spectrum: 0.5792944
color:
  saturation: 0.4900044
  lightness: 0.7070589
  brandStrength: 0.8808715
  rhythmicContrast: 0.7469375
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.3088973
name: 'Curaçao Transfer and Taxi Service #65'
